### ISSUE TITLE
Handling channels that have no modifier or are not indexed

### ISSUE THREAD

**Issue by gburca** [analogdevicesinc/libiio#25]
iio_channel_is_scan_element() returns false for channels without a modifier and that are not indexed, even though the kernel creates an entry in the scan_elements directory for them. Is that correct?

For example, a temperature sensor would have a single channel (so there's no need to index it), and it wouldn't need a modifier either. It would show up as "in_temp_raw" in the device directory and have "in_temp_{en|index|type}" files in the scan_elements directory.

**Comment by lclausen-adi** [comment]
Hi,

It's not intentional. Please send a patch.

Thanks,
- Lars

**Comment by abrauchli** [comment]
Potentially fixed by https://github.com/analogdevicesinc/libiio/pull/139

**Comment by gwendalcr** [comment]
#139  has been reverted by fb5fa69.  #273 addresses the problem, but how do I ensure it does not add a regression?

**Comment by gwendalcr** [comment]
#366 fixes the issue.

**Comment by rgetz** [comment]
Ok - since it's fixed, I will close. Thanks

**Comment by gwendalcr** [comment]
I was wrong, it is not fixed.
For simple attribute, like in_illuminance, found on driver like acpi_als, is_channel() returns false and iio_info does not report in_illuminance as a channel, iio_readdev can not read it.

With a trivial path (forcing is_channel("in_illuminance_..", true) to return true, similar to commit 4c6baf5e ("Local backend: Properly detect "timestamp" as a channel"), iio_genxml present acpi_als illuminance as channel:

from:
  <device id="iio:device0" name="acpi-als">
    <channel id="illuminance" type="input">
      <attribute name="raw" filename="in_illuminance_raw"/>
    </channel>
...

to:
  <device id="iio:device0" name="acpi-als">
    <channel id="illuminance" type="input">
      <scan-element index="0" format="le:S32/32&gt;&gt;0"/>
      <attribute name="raw" filename="in_illuminance_raw"/>
    </channel>
 
Since #273 is too generic, should we look at scan_elements/ directory to identify channels instead of the attributes at the root of iio:deviceX?
